version: '3'
services:
  db:
    build: .
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: develop
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
